# Generated by Django 6.1 on 2026-09-13 14:39
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3')], default='s1', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework/Library'), ('tool', 'Tool/Platform'), ('soft', 'Soft Skill')], default='language', max_length=20),
        ),
    ]
